# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\EMGControl\robot.ui'
#
# Created: Thu Jan 09 09:10:47 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_robotWidget(object):
    def setupUi(self, robotWidget):
        robotWidget.setObjectName(_fromUtf8("robotWidget"))
        robotWidget.resize(916, 600)
        robotWidget.setMinimumSize(QtCore.QSize(0, 600))
        robotWidget.setStyleSheet(_fromUtf8("background-color: rgba(0, 100, 100, 150);"))
        self.gridLayout = QtGui.QGridLayout(robotWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.socketControlFrame = QtGui.QFrame(robotWidget)
        self.socketControlFrame.setMinimumSize(QtCore.QSize(250, 0))
        self.socketControlFrame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.socketControlFrame.setStyleSheet(_fromUtf8("background-color: rgba(0, 170, 127, 255);"))
        self.socketControlFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.socketControlFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.socketControlFrame.setObjectName(_fromUtf8("socketControlFrame"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.socketControlFrame)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.label_9 = QtGui.QLabel(self.socketControlFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_7.addWidget(self.label_9)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.portNumEdit = QtGui.QLineEdit(self.socketControlFrame)
        self.portNumEdit.setStyleSheet(_fromUtf8("font: 9pt \"Courier New\";"))
        self.portNumEdit.setObjectName(_fromUtf8("portNumEdit"))
        self.horizontalLayout_7.addWidget(self.portNumEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.startButton = QtGui.QPushButton(self.socketControlFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(12)
        self.startButton.setFont(font)
        self.startButton.setFlat(True)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.horizontalLayout_13.addWidget(self.startButton)
        self.stopButton = QtGui.QPushButton(self.socketControlFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(12)
        self.stopButton.setFont(font)
        self.stopButton.setFlat(True)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.horizontalLayout_13.addWidget(self.stopButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.verticalLayout_6.addWidget(self.socketControlFrame)
        self.fingerControlFrame = QtGui.QFrame(robotWidget)
        self.fingerControlFrame.setEnabled(True)
        self.fingerControlFrame.setMinimumSize(QtCore.QSize(250, 0))
        self.fingerControlFrame.setMaximumSize(QtCore.QSize(150, 16777215))
        self.fingerControlFrame.setAutoFillBackground(False)
        self.fingerControlFrame.setStyleSheet(_fromUtf8("background-color: rgba(255, 115, 21, 200);\n"
""))
        self.fingerControlFrame.setObjectName(_fromUtf8("fingerControlFrame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.fingerControlFrame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.fingeControlLabel = QtGui.QLabel(self.fingerControlFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.fingeControlLabel.setFont(font)
        self.fingeControlLabel.setStyleSheet(_fromUtf8("background-color: rgb(117, 163, 170);\n"
"font: 12pt \"Courier New\";\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.fingeControlLabel.setObjectName(_fromUtf8("fingeControlLabel"))
        self.horizontalLayout_16.addWidget(self.fingeControlLabel)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem2)
        self.palmModelCheckBox = QtGui.QCheckBox(self.fingerControlFrame)
        self.palmModelCheckBox.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.palmModelCheckBox.setText(_fromUtf8(""))
        self.palmModelCheckBox.setObjectName(_fromUtf8("palmModelCheckBox"))
        self.horizontalLayout_16.addWidget(self.palmModelCheckBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_15 = QtGui.QLabel(self.fingerControlFrame)
        self.label_15.setAutoFillBackground(False)
        self.label_15.setStyleSheet(_fromUtf8("font: 9pt \"Courier New\";\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_15.addWidget(self.label_15)
        self.spinBox_13 = QtGui.QSpinBox(self.fingerControlFrame)
        self.spinBox_13.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.spinBox_13.setMaximum(75)
        self.spinBox_13.setObjectName(_fromUtf8("spinBox_13"))
        self.horizontalLayout_15.addWidget(self.spinBox_13)
        self.thumbYSlide = QtGui.QSlider(self.fingerControlFrame)
        self.thumbYSlide.setStyleSheet(_fromUtf8("background-color: rgba(170, 170, 255, 200);\n"
"background-color: rgba(255, 115, 21, 150);\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.thumbYSlide.setMaximum(75)
        self.thumbYSlide.setOrientation(QtCore.Qt.Horizontal)
        self.thumbYSlide.setObjectName(_fromUtf8("thumbYSlide"))
        self.horizontalLayout_15.addWidget(self.thumbYSlide)
        self.thumbYCheckBox = QtGui.QCheckBox(self.fingerControlFrame)
        self.thumbYCheckBox.setText(_fromUtf8(""))
        self.thumbYCheckBox.setObjectName(_fromUtf8("thumbYCheckBox"))
        self.horizontalLayout_15.addWidget(self.thumbYCheckBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_10 = QtGui.QLabel(self.fingerControlFrame)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setStyleSheet(_fromUtf8("font: 9pt \"Courier New\";\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_8.addWidget(self.label_10)
        self.spinBox_8 = QtGui.QSpinBox(self.fingerControlFrame)
        self.spinBox_8.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.spinBox_8.setMaximum(75)
        self.spinBox_8.setObjectName(_fromUtf8("spinBox_8"))
        self.horizontalLayout_8.addWidget(self.spinBox_8)
        self.thumbSlide = QtGui.QSlider(self.fingerControlFrame)
        self.thumbSlide.setStyleSheet(_fromUtf8("background-color: rgba(170, 170, 255, 200);\n"
"background-color: rgba(255, 115, 21, 150);\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.thumbSlide.setMaximum(75)
        self.thumbSlide.setOrientation(QtCore.Qt.Horizontal)
        self.thumbSlide.setObjectName(_fromUtf8("thumbSlide"))
        self.horizontalLayout_8.addWidget(self.thumbSlide)
        self.thumbChectBox = QtGui.QCheckBox(self.fingerControlFrame)
        self.thumbChectBox.setText(_fromUtf8(""))
        self.thumbChectBox.setObjectName(_fromUtf8("thumbChectBox"))
        self.horizontalLayout_8.addWidget(self.thumbChectBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_11 = QtGui.QLabel(self.fingerControlFrame)
        self.label_11.setStyleSheet(_fromUtf8("font: 9pt \"Courier New\";\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_9.addWidget(self.label_11)
        self.spinBox_9 = QtGui.QSpinBox(self.fingerControlFrame)
        self.spinBox_9.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.spinBox_9.setMaximum(75)
        self.spinBox_9.setObjectName(_fromUtf8("spinBox_9"))
        self.horizontalLayout_9.addWidget(self.spinBox_9)
        self.foreSlide = QtGui.QSlider(self.fingerControlFrame)
        self.foreSlide.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.foreSlide.setMaximum(75)
        self.foreSlide.setOrientation(QtCore.Qt.Horizontal)
        self.foreSlide.setObjectName(_fromUtf8("foreSlide"))
        self.horizontalLayout_9.addWidget(self.foreSlide)
        self.foreCheckBox = QtGui.QCheckBox(self.fingerControlFrame)
        self.foreCheckBox.setText(_fromUtf8(""))
        self.foreCheckBox.setObjectName(_fromUtf8("foreCheckBox"))
        self.horizontalLayout_9.addWidget(self.foreCheckBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_12 = QtGui.QLabel(self.fingerControlFrame)
        self.label_12.setStyleSheet(_fromUtf8("font: 9pt \"Courier New\";\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_10.addWidget(self.label_12)
        self.spinBox_10 = QtGui.QSpinBox(self.fingerControlFrame)
        self.spinBox_10.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.spinBox_10.setMaximum(75)
        self.spinBox_10.setObjectName(_fromUtf8("spinBox_10"))
        self.horizontalLayout_10.addWidget(self.spinBox_10)
        self.middleSlide = QtGui.QSlider(self.fingerControlFrame)
        self.middleSlide.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.middleSlide.setMaximum(75)
        self.middleSlide.setOrientation(QtCore.Qt.Horizontal)
        self.middleSlide.setObjectName(_fromUtf8("middleSlide"))
        self.horizontalLayout_10.addWidget(self.middleSlide)
        self.middleCheckBox = QtGui.QCheckBox(self.fingerControlFrame)
        self.middleCheckBox.setText(_fromUtf8(""))
        self.middleCheckBox.setObjectName(_fromUtf8("middleCheckBox"))
        self.horizontalLayout_10.addWidget(self.middleCheckBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_13 = QtGui.QLabel(self.fingerControlFrame)
        self.label_13.setStyleSheet(_fromUtf8("font: 9pt \"Courier New\";\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_11.addWidget(self.label_13)
        self.spinBox_11 = QtGui.QSpinBox(self.fingerControlFrame)
        self.spinBox_11.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.spinBox_11.setMaximum(75)
        self.spinBox_11.setObjectName(_fromUtf8("spinBox_11"))
        self.horizontalLayout_11.addWidget(self.spinBox_11)
        self.ringSlide = QtGui.QSlider(self.fingerControlFrame)
        self.ringSlide.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.ringSlide.setMaximum(75)
        self.ringSlide.setOrientation(QtCore.Qt.Horizontal)
        self.ringSlide.setObjectName(_fromUtf8("ringSlide"))
        self.horizontalLayout_11.addWidget(self.ringSlide)
        self.ringCheckBox = QtGui.QCheckBox(self.fingerControlFrame)
        self.ringCheckBox.setText(_fromUtf8(""))
        self.ringCheckBox.setObjectName(_fromUtf8("ringCheckBox"))
        self.horizontalLayout_11.addWidget(self.ringCheckBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_14 = QtGui.QLabel(self.fingerControlFrame)
        self.label_14.setStyleSheet(_fromUtf8("font: 9pt \"Courier New\";\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_12.addWidget(self.label_14)
        self.spinBox_12 = QtGui.QSpinBox(self.fingerControlFrame)
        self.spinBox_12.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.spinBox_12.setMaximum(75)
        self.spinBox_12.setObjectName(_fromUtf8("spinBox_12"))
        self.horizontalLayout_12.addWidget(self.spinBox_12)
        self.littleSlide = QtGui.QSlider(self.fingerControlFrame)
        self.littleSlide.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.littleSlide.setMaximum(75)
        self.littleSlide.setOrientation(QtCore.Qt.Horizontal)
        self.littleSlide.setObjectName(_fromUtf8("littleSlide"))
        self.horizontalLayout_12.addWidget(self.littleSlide)
        self.littleCheckBox = QtGui.QCheckBox(self.fingerControlFrame)
        self.littleCheckBox.setText(_fromUtf8(""))
        self.littleCheckBox.setObjectName(_fromUtf8("littleCheckBox"))
        self.horizontalLayout_12.addWidget(self.littleCheckBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addWidget(self.fingerControlFrame)
        self.armControlFrame = QtGui.QFrame(robotWidget)
        self.armControlFrame.setEnabled(True)
        self.armControlFrame.setMinimumSize(QtCore.QSize(250, 0))
        self.armControlFrame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.armControlFrame.setAutoFillBackground(False)
        self.armControlFrame.setStyleSheet(_fromUtf8("background-color: rgba(170, 170, 255, 200);"))
        self.armControlFrame.setObjectName(_fromUtf8("armControlFrame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.armControlFrame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.armControlLabel = QtGui.QLabel(self.armControlFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.armControlLabel.setFont(font)
        self.armControlLabel.setStyleSheet(_fromUtf8("background-color: rgb(117, 163, 170);\n"
"font: 75 12pt \"Courier New\";\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.armControlLabel.setObjectName(_fromUtf8("armControlLabel"))
        self.verticalLayout_2.addWidget(self.armControlLabel)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.armControlFrame)
        self.label.setStyleSheet(_fromUtf8("font: 9pt \"Courier New\";\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.spinBox = QtGui.QSpinBox(self.armControlFrame)
        self.spinBox.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.spinBox.setMinimum(-180)
        self.spinBox.setMaximum(180)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout.addWidget(self.spinBox)
        self.shoulderXSlide = QtGui.QSlider(self.armControlFrame)
        self.shoulderXSlide.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.shoulderXSlide.setMinimum(-180)
        self.shoulderXSlide.setMaximum(180)
        self.shoulderXSlide.setSingleStep(1)
        self.shoulderXSlide.setOrientation(QtCore.Qt.Horizontal)
        self.shoulderXSlide.setObjectName(_fromUtf8("shoulderXSlide"))
        self.horizontalLayout.addWidget(self.shoulderXSlide)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.armControlFrame)
        self.label_2.setStyleSheet(_fromUtf8("font: 9pt \"Courier New\";\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_2 = QtGui.QSpinBox(self.armControlFrame)
        self.spinBox_2.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.spinBox_2.setMinimum(-150)
        self.spinBox_2.setMaximum(90)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.horizontalLayout_2.addWidget(self.spinBox_2)
        self.shoulderZSlide = QtGui.QSlider(self.armControlFrame)
        self.shoulderZSlide.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.shoulderZSlide.setMinimum(-150)
        self.shoulderZSlide.setMaximum(90)
        self.shoulderZSlide.setOrientation(QtCore.Qt.Horizontal)
        self.shoulderZSlide.setObjectName(_fromUtf8("shoulderZSlide"))
        self.horizontalLayout_2.addWidget(self.shoulderZSlide)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.armControlFrame)
        self.label_3.setStyleSheet(_fromUtf8("font: 9pt \"Courier New\";\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBox_3 = QtGui.QSpinBox(self.armControlFrame)
        self.spinBox_3.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.spinBox_3.setMinimum(-90)
        self.spinBox_3.setMaximum(90)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.horizontalLayout_3.addWidget(self.spinBox_3)
        self.armYSlide = QtGui.QSlider(self.armControlFrame)
        self.armYSlide.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.armYSlide.setMinimum(-90)
        self.armYSlide.setMaximum(90)
        self.armYSlide.setOrientation(QtCore.Qt.Horizontal)
        self.armYSlide.setObjectName(_fromUtf8("armYSlide"))
        self.horizontalLayout_3.addWidget(self.armYSlide)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.armControlFrame)
        self.label_4.setStyleSheet(_fromUtf8("font: 9pt \"Courier New\";\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.spinBox_4 = QtGui.QSpinBox(self.armControlFrame)
        self.spinBox_4.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.spinBox_4.setMinimum(-90)
        self.spinBox_4.setMaximum(150)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.horizontalLayout_4.addWidget(self.spinBox_4)
        self.armXSlide = QtGui.QSlider(self.armControlFrame)
        self.armXSlide.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.armXSlide.setMinimum(-90)
        self.armXSlide.setMaximum(150)
        self.armXSlide.setOrientation(QtCore.Qt.Horizontal)
        self.armXSlide.setObjectName(_fromUtf8("armXSlide"))
        self.horizontalLayout_4.addWidget(self.armXSlide)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_7 = QtGui.QLabel(self.armControlFrame)
        self.label_7.setStyleSheet(_fromUtf8("font: 9pt \"Courier New\";\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_14.addWidget(self.label_7)
        self.spinBox_7 = QtGui.QSpinBox(self.armControlFrame)
        self.spinBox_7.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.spinBox_7.setMinimum(-90)
        self.spinBox_7.setMaximum(150)
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.horizontalLayout_14.addWidget(self.spinBox_7)
        self.foreArmXSlide = QtGui.QSlider(self.armControlFrame)
        self.foreArmXSlide.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.foreArmXSlide.setMinimum(-90)
        self.foreArmXSlide.setMaximum(150)
        self.foreArmXSlide.setOrientation(QtCore.Qt.Horizontal)
        self.foreArmXSlide.setObjectName(_fromUtf8("foreArmXSlide"))
        self.horizontalLayout_14.addWidget(self.foreArmXSlide)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.armControlFrame)
        self.label_5.setStyleSheet(_fromUtf8("font: 9pt \"Courier New\";\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.spinBox_5 = QtGui.QSpinBox(self.armControlFrame)
        self.spinBox_5.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.spinBox_5.setMinimum(-90)
        self.spinBox_5.setMaximum(90)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.horizontalLayout_5.addWidget(self.spinBox_5)
        self.palmXSlide = QtGui.QSlider(self.armControlFrame)
        self.palmXSlide.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.palmXSlide.setMinimum(-90)
        self.palmXSlide.setMaximum(90)
        self.palmXSlide.setOrientation(QtCore.Qt.Horizontal)
        self.palmXSlide.setObjectName(_fromUtf8("palmXSlide"))
        self.horizontalLayout_5.addWidget(self.palmXSlide)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(self.armControlFrame)
        self.label_6.setStyleSheet(_fromUtf8("font: 9pt \"Courier New\";\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.spinBox_6 = QtGui.QSpinBox(self.armControlFrame)
        self.spinBox_6.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.spinBox_6.setMinimum(-90)
        self.spinBox_6.setMaximum(90)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.horizontalLayout_6.addWidget(self.spinBox_6)
        self.palmZSlide = QtGui.QSlider(self.armControlFrame)
        self.palmZSlide.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.palmZSlide.setMinimum(-90)
        self.palmZSlide.setMaximum(90)
        self.palmZSlide.setOrientation(QtCore.Qt.Horizontal)
        self.palmZSlide.setObjectName(_fromUtf8("palmZSlide"))
        self.horizontalLayout_6.addWidget(self.palmZSlide)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_6.addWidget(self.armControlFrame)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 1, 1, 1)
        self.robotWidget = QtGui.QWidget(robotWidget)
        self.robotWidget.setMinimumSize(QtCore.QSize(640, 600))
        self.robotWidget.setStyleSheet(_fromUtf8("background-color: rgb(0, 170, 200);"))
        self.robotWidget.setObjectName(_fromUtf8("robotWidget"))
        self.gridLayout.addWidget(self.robotWidget, 0, 0, 1, 1)

        self.retranslateUi(robotWidget)
        QtCore.QObject.connect(self.spinBox_8, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.thumbSlide.setValue)
        QtCore.QObject.connect(self.spinBox_9, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.foreSlide.setValue)
        QtCore.QObject.connect(self.spinBox_10, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.middleSlide.setValue)
        QtCore.QObject.connect(self.spinBox_11, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.ringSlide.setValue)
        QtCore.QObject.connect(self.spinBox_12, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.littleSlide.setValue)
        QtCore.QObject.connect(self.spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.shoulderXSlide.setValue)
        QtCore.QObject.connect(self.spinBox_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.shoulderZSlide.setValue)
        QtCore.QObject.connect(self.spinBox_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.armYSlide.setValue)
        QtCore.QObject.connect(self.spinBox_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.armXSlide.setValue)
        QtCore.QObject.connect(self.spinBox_5, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.palmXSlide.setValue)
        QtCore.QObject.connect(self.spinBox_6, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.palmZSlide.setValue)
        QtCore.QObject.connect(self.shoulderZSlide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_2.setValue)
        QtCore.QObject.connect(self.armYSlide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_3.setValue)
        QtCore.QObject.connect(self.armXSlide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_4.setValue)
        QtCore.QObject.connect(self.palmXSlide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_5.setValue)
        QtCore.QObject.connect(self.palmZSlide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_6.setValue)
        QtCore.QObject.connect(self.thumbSlide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_8.setValue)
        QtCore.QObject.connect(self.foreSlide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_9.setValue)
        QtCore.QObject.connect(self.middleSlide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_10.setValue)
        QtCore.QObject.connect(self.ringSlide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_11.setValue)
        QtCore.QObject.connect(self.littleSlide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_12.setValue)
        QtCore.QObject.connect(self.shoulderZSlide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_2.setValue)
        QtCore.QObject.connect(self.shoulderXSlide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox.setValue)
        QtCore.QObject.connect(self.foreArmXSlide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_7.setValue)
        QtCore.QObject.connect(self.spinBox_7, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.foreArmXSlide.setValue)
        QtCore.QObject.connect(self.spinBox_13, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.thumbYSlide.setValue)
        QtCore.QObject.connect(self.thumbYSlide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_13.setValue)
        QtCore.QObject.connect(self.palmXSlide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_5.setValue)
        QtCore.QObject.connect(self.palmXSlide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_5.setValue)
        QtCore.QObject.connect(self.thumbYSlide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_13.setValue)
        QtCore.QMetaObject.connectSlotsByName(robotWidget)

    def retranslateUi(self, robotWidget):
        robotWidget.setWindowTitle(_translate("robotWidget", "Form", None))
        self.label_9.setText(_translate("robotWidget", "Port", None))
        self.portNumEdit.setText(_translate("robotWidget", "9558", None))
        self.startButton.setText(_translate("robotWidget", "start", None))
        self.stopButton.setText(_translate("robotWidget", "stop", None))
        self.fingeControlLabel.setText(_translate("robotWidget", "    Finger Control", None))
        self.label_15.setText(_translate("robotWidget", "ThumbY", None))
        self.label_10.setText(_translate("robotWidget", "Thumb ", None))
        self.label_11.setText(_translate("robotWidget", "Fore  ", None))
        self.label_12.setText(_translate("robotWidget", "Middle", None))
        self.label_13.setText(_translate("robotWidget", "Ring  ", None))
        self.label_14.setText(_translate("robotWidget", "Little", None))
        self.armControlLabel.setText(_translate("robotWidget", "      Arm Control", None))
        self.label.setText(_translate("robotWidget", "ShoulderX", None))
        self.label_2.setText(_translate("robotWidget", "ShouldreZ", None))
        self.label_3.setText(_translate("robotWidget", "Arm     Y", None))
        self.label_4.setText(_translate("robotWidget", "Arm     X", None))
        self.label_7.setText(_translate("robotWidget", "ForeArm Y", None))
        self.label_5.setText(_translate("robotWidget", "Palm    X", None))
        self.label_6.setText(_translate("robotWidget", "Palm    Z", None))

